#pragma once
#include "Lgs_Types.h"
#include "data/LgsErrors.h"
#include "exprs/LgsBinaryExpr.h"
#include <map>

class LgsGeneric;
class LgsSubType;
class LgsSet;
class LgsAny;
class LgsByte;
class LgsSize;
class LgsPtr;
class LgsDouble;
class LgsFloat;
class LgsVec;
class LgsVectorExpr;
class LgsChar;
class LgsVariable;
class LgsSArray;
class LgsNullable;
class LgsUInt;
class LgsShort;
class LgsTypePair;
class LgsLong;
class LgsHashMap;
class LgsVTable;
class LgsFuncType;
class LgsInterface;
class LgsObject;
class LgsBool;
class LgsMap;
class LgsEnum;
class LgsInt;
class LgsDArray;
class LgsIterable;
class LgsStr;
class LgsExpr;
class LgsFuncCall;
class LgsField;
class LgsFunc;
class LgsLLVMGen;

class LgsType {
public:
    bool isInt = false;
    bool isFloat = false;
    bool isPrimitive = false;
    bool isUnsigned = false;
    bool isHeapAlloc = false;
    bool isGeneric = false;
    Type* IRType = nullptr;
    LgsLocation location;
    std::vector<LgsField*> fields;
    std::map<std::string, LgsFunc*> methods;

    virtual LgsField* getField(const std::string& fieldName);
    virtual LgsFunc* getMethod(const std::string& methodName);
    bool addField(LgsField* field);
    bool addMethod(LgsFunc* method);
    bool addEmptyMethod(const std::string& name);
    bool isVoid();
    bool isNumber() const;
    bool isBig();
    bool isUnknown();
    bool isSliceable();
    LgsType* extendInt();
    LgsType* applyIntBinOp(LgsBinOpType op, LgsType* other);
    static Value* orInt(LgsLLVMGen& cg, const LgsExpr* self, const LgsExpr* other);
    static Value* andInt(LgsLLVMGen& cg, LgsExpr* self, const LgsExpr* other);

    virtual Type* getIRType(LgsLLVMGen& cg) = 0;
    virtual size_t getSizeBytes() = 0;
    virtual LgsExpr* getZeroValue() = 0;
    virtual Lgs_RTType getRTType() = 0;
    virtual std::string getName() = 0;
    virtual std::string pname(); // pretty name
    virtual bool equals(LgsType* other);
    virtual bool canCastTo(LgsType* other) = 0;
    virtual LgsType* applyBinOp(LgsBinaryExpr* binExpr);
    virtual std::string strFormatPart() const = 0;
    virtual DIBasicType* getDebugType(LgsLLVMGen& cg);
    virtual void hashNode(size_t& oldHash);
    virtual LgsType* clone();

    LgsAny* asAny();
    LgsChar* asChar();
    LgsStr* asStr();
    LgsBool* asBool();
    LgsByte* asByte();
    LgsInt* asInt();
    LgsShort* asShort();
    LgsLong* asLong();
    LgsSize* asSize();
    LgsUInt* asUInt();
    LgsFloat* asFloat();
    LgsDouble* asDouble();
    LgsFuncType* asFuncType();
    LgsObject* asObject();
    LgsInterface* asInterface();
    LgsEnum* asEnum();
    LgsGeneric* asGeneric();
    LgsIterable* asIterable();
    LgsSArray* asSArray();
    LgsDArray* asDArray();
    LgsSet* asSet();
    LgsVec* asVec();
    LgsPtr* asPtr();
    LgsMap* asMap();
    LgsTypePair* asPair();
    LgsSubType* asSubtype();
    LgsNullable* asNullable();

    virtual LgsExpr* addConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* subConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* mulConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* divConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* modConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* bitAndConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* bitOrConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* bitXorConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* lshiftConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* rshiftConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* eqConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* neConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* ltConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* gtConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* geConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* leConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* andConst(LgsExpr* self, LgsExpr* other);
    virtual LgsExpr* orConst(LgsExpr* self, LgsExpr* other);
    virtual Value* addIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* subIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* mulIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* divIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* modIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* bitAndIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* bitOrIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* bitXorIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* lshiftIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* rshiftIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* eqIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* neIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* ltIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* gtIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* geIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* leIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* andIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual Value* orIR(LgsLLVMGen& cg, LgsExpr* self, LgsExpr* other);
    virtual ~LgsType() = default;
};
