#pragma once
#include <iosfwd>
#include <sstream>

class LgsSubType;
class LgsEnum;
class LgsIntConst;
class LgsNull;
class LgsMetaVar;
class LgsJson;
class LgsTypeExpr;
class LgsVectorExpr;
class LgsIOStmt;
class LgsSwitch;
class LgsIOPair;
class LgsParam;
class LgsMainFunc;
class LgsFunc;
class LgsField;
class LgsTestFile;
class LgsInterface;
class LgsTernaryExpr;
class LgsVec;
class LgsInterfaceFile;
class LgsObjectFile;
class LgsPostfixExpr;
class LgsDeferStmt;
class LgsInfiniteLoop;
class LgsObject;
class LgsWhileLoop;
class LgsFuncType;
class LgsIterable;
class LgsFile;
class LgsCoroutine;
class LgsPrefixExpr;
class LgsDArray;
class LgsValue;
class LgsVariable;
class LgsStrConst;
class LgsHashMap;
class LgsExpr;
class LgsType;
class LgsContinue;
class LgsBreak;
class LgsReturn;
class LgsForeachLoop;
class LgsRangeLoop;
class LgsStmtsBlock;
class LgsStmt;
class LgsMainFile;
class LgsApp;
class LgsCast;
class LgsVarDec;
class LgsInstance;
class LgsIterIndex;
class LgsSelection;
class LgsFuncCall;
class LgsBinaryExpr;
class LgsArrayExpr;
class LgsIfStmt;
class LgsAssignment;
class LgsForLoop;
struct LgsSymbol;
struct LgsIndex;

class LgsFormatter {
public:
    uint16_t indentLevel = 0;
    std::stringstream formatted;

    void formatFile(LgsFile* file);
    void formatMainFile(LgsMainFile* mainFile);
    void formatTestFile(LgsTestFile* testFile);
    void formatObjectFile(LgsObjectFile* objFile);
    void formatInterfaceFile(LgsInterfaceFile* interfaceFile);
    void formatObject(LgsObject* obj);
    void formatInterface(LgsInterface* interface);
    void formatEnum(const LgsEnum* enum_);
    void formatSubtype(LgsSubType* subtype);
    void formatField(const LgsField* field);
    void formatFuncHeader(const LgsFunc* func);
    void formatFunc(const LgsFunc* func);
    void formatParam(LgsParam& param);
    void formatIOPair(LgsIOPair* ioPair, LgsObject* obj);
    void formatStmt(LgsStmt* stmt);
    void formatStmtsBlock(const LgsStmtsBlock* stmtsBlock);
    void formatVarDec(LgsVarDec* varDec);
    void formatAssignment(LgsAssignment* assignment);
    void formatIfStmt(LgsIfStmt* ifStmt);
    void formatSwitch(LgsSwitch* switchStmt);
    void formatWhileLoop(LgsWhileLoop* whileLoop);
    void formatLoopStmt(LgsForLoop* loopStmt);
    void formatRangeLoop(LgsRangeLoop* rangeLoop);
    void formatForeachLoop(LgsForeachLoop* foreachLoop);
    void formatInfiniteLoop(const LgsInfiniteLoop* infiniteLoop);
    void formatReturnStmt(LgsReturn* returnStmt);
    void formatContinueStmt(const LgsContinue* continueStmt);
    void formatBreakStmt(const LgsBreak* breakStmt);
    void formatCoroutine(const LgsCoroutine* coroutine);
    void formatDeferStmt(const LgsDeferStmt* deferStmt);
    void formatIOStmt(const LgsIOStmt* ioStmt);
    void formatExpr(LgsExpr*& expr);
    void formatBinaryExpr(LgsBinaryExpr* binaryExpr);
    void formatTernaryExpr(LgsTernaryExpr* ternary);
    void formatCast(LgsCast* cast);
    void formatArrayExpr(LgsArrayExpr* arrayExpr);
    void formatStaticArray(const LgsArrayExpr* arrayExpr);
    void formatDynamicArray(LgsArrayExpr* arrayExpr);
    void formatHashMap(LgsHashMap* hashMap);
    void formatVectorExpr(const LgsVectorExpr* vectorExpr);
    void formatVariable(const LgsVariable* variable);
    void formatSelection(const LgsSelection* selection);
    void formatFuncCall(LgsFuncCall* funcCall);
    void formatPrefixExpr(LgsPrefixExpr* prefixExpr);
    void formatPostfixExpr(LgsPostfixExpr* postfixExpr);
    void formatStrConst(const LgsStrConst* strConst);
    void formatTypeExpr(LgsTypeExpr* typeExpr);
    void formatJson(const LgsJson* jsonStmt);
    void formatInstance(LgsInstance* instance);
    void formatNull(LgsNull* null);
    void formatIntConst(const LgsIntConst* intConst);
    void formatInterfaceInstance(LgsInstance* instance, LgsInterface* interface);
    void formatIterIndex(LgsIterIndex* iterIndex);
    void formatIndex(LgsIterIndex* iterIndex);
    void formatSlice(LgsIterIndex* iterIndex);
    void formatLoopMetaVar(LgsMetaVar* metaVar);
    void insert(const std::string& text);
    void newLine(bool withIndent = false, uint8_t lines = 1);
};
