#pragma once
#include "types/LgsEnum.h"
#include <sstream>

class LgsMetaVar;
class LgsJson;
class LgsTypeExpr;
class LgsVectorExpr;
class LgsIOStmt;
class LgsSwitch;
class LgsIOPair;
class LgsParam;
class LgsMainFunc;
class LgsFunc;
class LgsField;
class LgsTestFile;
class LgsInterface;
class LgsTernaryExpr;
class LgsVec;
class LgsInterfaceFile;
class LgsObjectFile;
class LgsPostfixExpr;
class LgsDeferStmt;
class LgsInfiniteLoop;
class LgsObject;
class LgsWhileLoop;
class LgsFuncType;
class LgsIterable;
class LgsFile;
class LgsCoroutine;
class LgsPrefixExpr;
class LgsDArray;
class LgsValue;
class LgsVariable;
class LgsStrConst;
class LgsHashMap;
class LgsExpr;
class LgsType;
class LgsContinue;
class LgsBreak;
class LgsReturn;
class LgsForeachLoop;
class LgsRangeLoop;
class LgsStmtsBlock;
class LgsStmt;
class LgsMainFile;
class LgsApp;
class LgsCast;
class LgsVarDec;
class LgsInstance;
class LgsIterIndex;
class LgsSelection;
class LgsFuncCall;
class LgsBinaryExpr;
class LgsArrayExpr;
class LgsIfStmt;
class LgsAssignment;
class LgsForLoop;
struct LgsSymbol;
struct LgsIndex;

class LgsJsonParser final {
public:
    std::stringstream json;
    bool pretty = false;

    void parseFile(LgsFile* file);
    void parseMainFile(LgsMainFile* mainFile);
    void parseTestFile(LgsTestFile* testFile);
    void parseObject(LgsObject* obj);
    void parseInterface(LgsInterface* interface);
    void parseEnum(LgsEnum* enum_);
    void parseSubtype(LgsSubType* subtype);
    void parseField(const LgsField* field);
    void parseFunc(const LgsFunc* func);
    void parseParam(const LgsParam* param);
    void parseIOPair(LgsIOPair* ioPair, LgsObject* obj);
    void parseStmt(LgsStmt* stmt);
    void parseStmtsBlock(const LgsStmtsBlock* stmtsBlock);
    void parseVarDec(const LgsVarDec* varDec);
    void parseAssignment(LgsAssignment* assignment);
    void parseIfStmt(LgsIfStmt* ifStmt);
    void parseSwitch(LgsSwitch* switchStmt);
    void parseWhileLoop(LgsWhileLoop* whileLoop);
    void parseLoopStmt(LgsForLoop* loopStmt);
    void parseRangeLoop(LgsRangeLoop* rangeLoop);
    void parseForeachLoop(LgsForeachLoop* foreachLoop);
    void parseInfiniteLoop(const LgsInfiniteLoop* infiniteLoop);
    void parseReturnStmt(LgsReturn* returnStmt);
    void parseContinueStmt(const LgsContinue* continueStmt);
    void parseBreakStmt(const LgsBreak* breakStmt);
    void parseCoroutine(const LgsCoroutine* coroutine);
    void parseDeferStmt(const LgsDeferStmt* deferStmt);
    void parseIOStmt(const LgsIOStmt* ioStmt);
    void parseExpr(LgsExpr*& expr);
    void parseBinaryExpr(const LgsBinaryExpr* binaryExpr);
    void parseTernaryExpr(LgsTernaryExpr* ternary);
    void parseCast(LgsCast* cast);
    void parseArrayExpr(LgsArrayExpr* arrayExpr);
    void parseStaticArray(const LgsArrayExpr* arrayExpr);
    void parseDynamicArray(LgsArrayExpr* arrayExpr);
    void parseHashMap(LgsHashMap* hashMap);
    void parseVectorExpr(const LgsVectorExpr* vectorExpr);
    void parseVariable(const LgsVariable* variable);
    void parseSelection(LgsSelection* selection);
    void parseFuncCall(LgsFuncCall* funcCall);
    void parsePrefixExpr(LgsPrefixExpr* prefixExpr);
    void parsePostfixExpr(LgsPostfixExpr* postfixExpr);
    void parseStrConst(const LgsStrConst* strConst);
    void parseTypeExpr(LgsTypeExpr* typeExpr);
    void parseJson(const LgsJson* jsonStmt);
    void parseInstance(LgsInstance* instance);
    void parseNull(LgsNull* null);
    void parseIntConst(const LgsIntConst* intConst);
    void parseInterfaceInstance(LgsInstance* instance, LgsInterface* interface);
    void parseIterIndex(LgsIterIndex* iterIndex);
    void parseIndex(LgsIterIndex* iterIndex);
    void parseSlice(LgsIterIndex* iterIndex);
    void parseLoopMetaVar(LgsMetaVar* metaVar);

    void addString(const std::string& v);
    void addBool(bool v);
    void openArray();
    void closeArray(bool withComma = false);
    void openObject();
    void closeObject(bool withComma = false);
    void openKey(const std::string& v);
    void openKeyArray(const std::string& v);
    void openKeyObject(const std::string& v);
    void addKeyValueStr(const std::string& k, const std::string& v, bool withComma = false);
    void addKeyValueInt(const std::string& k, size_t v, bool withComma = false);
    void addKeyValueBool(const std::string& k, bool v, bool withComma = false);
    void addComma();
};
