#pragma once

#define LOGOS_FILE_EXTENSION ".lgs"
#define LOGOS_SRC_DIR "src"
#define LOGOS_ENVS_DIR "envs"
#define LOGOS_BUILD_DIR "build"
#define LOGOS_BUILD_IR "IR"
#define LOGOS_MAIN_FILE_NAME "Main"
#define LOGOS_APP_FILE_NAME "App"
#define LOGOS_MAIN_FUNC_NAME "main"
#define LOGOS_SELF "self"
#define LOGOS_LOOP_IS_FIRST "for.isFirst"
#define LOGOS_LOOP_IS_LAST "for.isLast"
#define LOGOS_OBJECT_FILE "main.o"
#define LOGOS_DEBUG_FILE "paths.dat"
#define LOGOS_EXECUTABLE_FILE "output"
#define LOGOS_STR_FORMAT_PART "%v"
#define LOGOS_MSG_PLACEHOLDER "%s"
#define LOGOS_ERROR_STR "\033[1;31mError:\033[0m "

#define BLOCK_NAME_IF_TRUE "if_true"
#define BLOCK_NAME_DEFAULT_CASE "default"
#define BLOCK_NAME_EXIT_PATTERN "exit_pattern_matching"
#define BLOCK_NAME_CASE_PREFIX "case_"
#define BLOCK_NAME_ENTRY "entry"
#define BLOCK_NAME_RETURN_BLOCK "return"
#define BLOCK_NAME_SUSPEND "suspend"
#define BLOCK_NAME_RESUME "resume"
#define BLOCK_NAME_IF_FALSE "if_false"
#define BLOCK_NAME_ELSE "else"
#define BLOCK_NAME_ELSE_IF "else_if"
#define BLOCK_NAME_ELSE_IF_CHECK "else_if_check"
#define BLOCK_NAME_LOOP_COND "loop_cond"
#define BLOCK_NAME_LOOP_BODY "loop_body"
#define BLOCK_NAME_LOOP_EXIT "loop_exit"
#define BLOCK_NAME_BREAK "break"
#define BLOCK_NAME_IS_NULL "is_null_block"
#define BLOCK_NAME_NOT_NULL "not_null_block"
#define BLOCK_NAME_CLEANUP "cleanup"
#define BLOCK_NAME_CLEANUP_LOOP_COND "cleanup_loop_cond"
#define BLOCK_NAME_CLEANUP_LOOP_BODY "cleanup_loop_body"
#define BLOCK_NAME_CLEANUP_LOOP_EXIT "cleanup_loop_exit"
#define BLOCK_NAME_CLEANUP_LOOP_INC "cleanup_loop_inc"
#define BLOCK_NAME_CLEANUP_FREE_ELEMENT "cleanup_free_element"

