#pragma once

/**
 * Generic base struct for warnings and errors.
 */
struct LgsBaseMsg {
    const char* const msg;
    size_t const errCode;
    LgsBaseMsg(const char* msg, const size_t code) : msg(msg), errCode(code) {}
};

/** Templates errors. Should not be returned directly but formatted and wrapped around with another struct */
static inline size_t errCodeStart = 10000;
inline LgsBaseMsg E10000{"main() function is not defined in main.lgs file.", errCodeStart++};
inline LgsBaseMsg E10001{"Expected type %s does not match the given type %s.", errCodeStart++};
inline LgsBaseMsg E10002{"%s must be an iterable.", errCodeStart++};
inline LgsBaseMsg E10003{"Index %s is out of bounds.", errCodeStart++};
inline LgsBaseMsg E10004{"Function %s must return an expression of type %s. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10005{"%s is not a member of %s.", errCodeStart++};
inline LgsBaseMsg E10006{"%s is not defined.", errCodeStart++};
inline LgsBaseMsg E10007{"File %s is duplicate. All files in a project must be unique.", errCodeStart++};
inline LgsBaseMsg E10008{"main.lgs could not be found in src directory.", errCodeStart++};
inline LgsBaseMsg E10009{"Duplicate Main files were found in the project. Locations:%s.", errCodeStart++};
inline LgsBaseMsg E10010{"Not a root path of a Logos project.", errCodeStart++};
inline LgsBaseMsg E10011{"%s is already declared.", errCodeStart++};
inline LgsBaseMsg E10012{"null cannot have '?' suffix.", errCodeStart++};
inline LgsBaseMsg E10013{"Field %s has function type. Declare it as a standard function instead.", errCodeStart++};
inline LgsBaseMsg E10014{"Self type not allowed.", errCodeStart++};
inline LgsBaseMsg E10015{"Function with name '%s' was found but it doesnt match the parameters.\nGiven:\t  %s\nExpected:  %s.", errCodeStart++};
inline LgsBaseMsg E10016{"Object %s does not fully implement %s.\n%s.", errCodeStart++};
inline LgsBaseMsg E10017{"break must be inside a for loop.", errCodeStart++};
inline LgsBaseMsg E10018{"%s cannot cast to type %s.", errCodeStart++};
inline LgsBaseMsg E10019{"activeEnv %s could not be found in the envs directory.", errCodeStart++};
inline LgsBaseMsg E10020{"Environment %s must declare the required variable %s.", errCodeStart++};
inline LgsBaseMsg E10021{"%s and %s must be the same type. Given: %s and %s.", errCodeStart++};
inline LgsBaseMsg E10022{"%s cannot be instantiated.", errCodeStart++};
inline LgsBaseMsg E10023{"null can only be assigned to nullable type.", errCodeStart++};
inline LgsBaseMsg E10024{"null must have an explict nullable type.", errCodeStart++};
inline LgsBaseMsg E10025{"Only interfaces are allowed in implements. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10026{"Function %s must return an expression of type %s. None was given.", errCodeStart++};
inline LgsBaseMsg E10027{"Void function can either return Void type or empty return.", errCodeStart++};
inline LgsBaseMsg E10028{"Default parameters must be defined lastly.", errCodeStart++};
inline LgsBaseMsg E10029{"Mixed array types. All dimensions must be either sized or unsized.", errCodeStart++};
inline LgsBaseMsg E10030{"Non-public field %s is used outside its parent object %s.", errCodeStart++};
inline LgsBaseMsg E10031{"Non-public method %s is used outside its parent object %s.", errCodeStart++};
inline LgsBaseMsg E10032{"Singleton object %s cannot be instantiated.", errCodeStart++};
inline LgsBaseMsg E10033{"Type name must start with an uppercase letter.", errCodeStart++};
inline LgsBaseMsg E10034{"Lambda function cannot be mutable.", errCodeStart++};
inline LgsBaseMsg E10035{"Index of %s has %s level which is too deep. Max level: %s.", errCodeStart++};
inline LgsBaseMsg E10036{"Cannot be indexed with type %s.", errCodeStart++};
inline LgsBaseMsg E10037{"Left index of slice must be less or equal than the right index.", errCodeStart++};
inline LgsBaseMsg E10038{"continue must be inside a for loop.", errCodeStart++};
inline LgsBaseMsg E10039{"main() function accepts only one optional parameter of type Str[].", errCodeStart++};
inline LgsBaseMsg E10040{"The number of variables in the for loop (%s) do not match the number of the iterables returned values (%s).", errCodeStart++};
inline LgsBaseMsg E10041{"Could not unpack iterable %s of type %s with %s variables.", errCodeStart++};
inline LgsBaseMsg E10042{"Type %s cannot be sliced.", errCodeStart++};
inline LgsBaseMsg E10043{"Default parameters and variadic arguments are not allowed in the same function.", errCodeStart++};
inline LgsBaseMsg E10044{"Value of switch case must be known at compile time. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10045{"Variadic argument cannot have default arguments.", errCodeStart++};
inline LgsBaseMsg E10046{"%s is not callable.", errCodeStart++};
inline LgsBaseMsg E10047{"External %s file '%s' was not found.", errCodeStart++};
inline LgsBaseMsg E10048{"Recursive non-nullable objects are not allowed.", errCodeStart++};
inline LgsBaseMsg E10049{"Not enough information to infer the type of %s.", errCodeStart++};
inline LgsBaseMsg E10050{"Only integer values can be incremented (++) or decremented (--). Given: %s.", errCodeStart++};
inline LgsBaseMsg E10051{"%s is not mutable.", errCodeStart++};
inline LgsBaseMsg E10052{"Spread operator in %s... must only be used with iterables. Given type: %s.", errCodeStart++};
inline LgsBaseMsg E10053{"'%s' is a Logos global name and cannot be redefined.", errCodeStart++};
inline LgsBaseMsg E10054{"Field %s is set more than one time.", errCodeStart++};
inline LgsBaseMsg E10055{"Function %s must return from all its paths.", errCodeStart++};
inline LgsBaseMsg E10056{"%s has multiple fields with the same name %s.", errCodeStart++};
inline LgsBaseMsg E10057{"Pattern matching expression %s must be of type Bool.", errCodeStart++};
inline LgsBaseMsg E10058{"Selection with '::' must be an object type.", errCodeStart++};
inline LgsBaseMsg E10059{"Unreachable code.", errCodeStart++};
inline LgsBaseMsg E10060{"for meta variables are only allowed inside a for loop.", errCodeStart++};
inline LgsBaseMsg E10061{"%s is not allowed in an infinite loop.", errCodeStart++};
inline LgsBaseMsg E10062{"Interface %s implements all its methods which is not allowed. Make at least one of the methods abstract (without implementation) or change it to object", errCodeStart++};
inline LgsBaseMsg E10063{"Interfaces must have at least one (abstract) method or field.", errCodeStart++};
inline LgsBaseMsg E10064{"Method '%s' is defined in multiple interfaces.", errCodeStart++};
inline LgsBaseMsg E10065{"%s is not allowed in a while loop.", errCodeStart++};
inline LgsBaseMsg E10066{"While loop condition %s must be of type Bool. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10067{"%s was not found.", errCodeStart++};
inline LgsBaseMsg E10068{"App version must be in the form of 1.0.0. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10069{"Too many scalars passed to %s.", errCodeStart++};
inline LgsBaseMsg E10070{"Invalid scalars %s for %s.", errCodeStart++};
inline LgsBaseMsg E10071{"break if must be inside an if statement.", errCodeStart++};
inline LgsBaseMsg E10072{"%s has multiple methods with the same name %s.", errCodeStart++};
inline LgsBaseMsg E10073{"Vector elements can only be numbers or vectors.", errCodeStart++};
inline LgsBaseMsg E10074{"Too many scalars for %s.", errCodeStart++};
inline LgsBaseMsg E10075{"Enum field values must all be the same type.", errCodeStart++};
inline LgsBaseMsg E10076{"'%s' is not defined between %s and %s.", errCodeStart++}; // operation, left-expr, right-expr
inline LgsBaseMsg E10077{"Enum field value must be of constant type.", errCodeStart++};
inline LgsBaseMsg E10078{"Defer functions must return Void. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10079{"Test file %s must be inside tests directory.", errCodeStart++};
inline LgsBaseMsg E10080{"Index %s was not found in iterable.", errCodeStart++};
inline LgsBaseMsg E10081{"Range-start type %s is not equal to the range-end type %s.", errCodeStart++};
inline LgsBaseMsg E10082{"Loop range %s must be an integer. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10083{"Method %s is an object method but was called as a class method.", errCodeStart++};
inline LgsBaseMsg E10084{"%s does not belong to an IO pair.", errCodeStart++};
inline LgsBaseMsg E10085{"Parsing error.", errCodeStart++};
inline LgsBaseMsg E10086{"Invalid Logos path: %s.", errCodeStart++};
inline LgsBaseMsg E10087{"Logos library cannot define a main() function.", errCodeStart++};
inline LgsBaseMsg E10088{"Bad character.", errCodeStart++};
inline LgsBaseMsg E10089{"%s can only be assigned to an instance of %s, not the object itself.", errCodeStart++};
inline LgsBaseMsg E10090{"%s can only prefix numbers. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10091{"'not' can only prefix Bool. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10092{"If condition must be of type Bool. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10093{"Cannot assign to Void type.", errCodeStart++};
inline LgsBaseMsg E10094{"%s is not a parameter of '%s'.", errCodeStart++};
inline LgsBaseMsg E10095{"Could not infer iterable type.", errCodeStart++};
inline LgsBaseMsg E10096{"Mixing named und position arguments is not allowed.", errCodeStart++};
inline LgsBaseMsg E10097{"switch statement must have at least one pattern.", errCodeStart++};
inline LgsBaseMsg E10098{"Argument %s is passed more than one time.", errCodeStart++};
inline LgsBaseMsg E10099{"Local names must start with a lowercase letter.", errCodeStart++};
inline LgsBaseMsg E10100{"Global variable '%s' must be declared const.", errCodeStart++};
inline LgsBaseMsg E10101{"Macro condition must be known at compile time.", errCodeStart++};
inline LgsBaseMsg E10102{"Macro condition must be of type Bool. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10103{"'%s' doesn't match the rows length. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10104{"'%s' doesn't match the columns length. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10105{"Too many elements for array of length: %s.", errCodeStart++};
inline LgsBaseMsg E10106{"Could not parse C file %s.", errCodeStart++};
inline LgsBaseMsg E10107{"Could not find C library %s.", errCodeStart++};
inline LgsBaseMsg E10108{"%s is not indexable.", errCodeStart++};
inline LgsBaseMsg E10109{"Expression of type %s cannot be set as default value.", errCodeStart++};
inline LgsBaseMsg E10110{"Unsigned number cannot be negative.", errCodeStart++};
inline LgsBaseMsg E10111{"Null pointer exception.", errCodeStart++};
inline LgsBaseMsg E10112{"Matrix rows/columns cannot be 0.", errCodeStart++};
inline LgsBaseMsg E10113{"Only nullable values can be unwrapped with '!'.", errCodeStart++};
inline LgsBaseMsg E10114{"Static array size must be known at compile time.", errCodeStart++};
inline LgsBaseMsg E10115{"Wrong number of generic arguments. Expected: %s. Given: %s.", errCodeStart++};
inline LgsBaseMsg E10116{"Could not replace generic type %s with actual type.", errCodeStart++};
inline LgsBaseMsg E10117{"Function call cannot be assigned to a value.", errCodeStart++};
