#pragma once
#include "LgsDefinitions.h"
#include "errors/LgsErrHandler.h"
#include <string>
#include <unordered_map>

enum LgsTokenType {
    T_LANGLE,
    T_RANGLE,
    T_LPAREN,
    T_RPAREN,
    T_LBRACK,
    T_RBRACK,
    T_LBRACE,
    T_RBRACE,
    T_STAR_LBRACE,
    T_STAR_RBRACE,
    T_DOT,
    T_COMMA,
    T_ARROW,
    T_DARROW,
    T_COLON,
    T_DOUBLE_COLON,
    T_EQUAL,
    T_DOUBLE_EQUAL,
    T_NOT_EQUAL,
    T_GE,
    T_LE,
    T_QUEST_MARK,
    T_EXCLA_MARK,
    T_TRIPLE_DOT,
    T_DOUBLE_DOT,
    T_WALRUS,
    T_EQUAL_PLUS,
    T_EQUAL_MINUS,
    T_EQUAL_STAR,
    T_EQUAL_SLASH,
    T_EQUAL_PERCENT,
    T_EQUAL_DOLLAR,
    T_EQUAL_AMPERSAND,
    T_EQUAL_PIPE,
    T_EQUAL_CARET,
    T_EQUAL_DOUBLE_CARET,
    T_EQUAL_DOUBLE_RANGLE,
    T_EQUAL_DOUBLE_LANGLE,
    T_INC,
    T_DEC,
    T_PLUS,
    T_MINUS,
    T_STAR,
    T_SLASH,
    T_SLIDER,
    T_PERCENT,
    T_AMPERSAND,
    T_PIPE,
    T_CARET,
    T_DOUBLE_CARET,
    T_DOLLAR,
    T_DOUBLE_LANGLE,
    T_DOUBLE_RANGLE,
    T_TYPE,
    T_OBJECT,
    T_SINGLETON,
    T_SELF_INSTANCE,
    T_SELF_CLASS,
    T_INTERFACE,
    T_PUBLIC,
    T_IMPLEMENTS,
    T_MUT,
    T_ENUM,
    T_GO,
    T_DEFER,
    T_IO,
    T_AND,
    T_OR,
    T_NOT,
    T_IN,
    T_IF,
    T_SWITCH,
    T_ELSE,
    T_THEN,
    T_WHILE,
    T_BREAK,
    T_CONTINUE,
    T_RETURN,
    T_IMPORT,
    T_VEC2,
    T_VEC3,
    T_VEC4,
    T_MATRIX,
    T_SET,
    T_FOR,
    T_FOR_I,
    T_FOR_IS_FIRST,
    T_FOR_IS_LAST,
    T_FOR_ELEMENT,
    T_FOR_EVER,
    T_BOOL,
    T_INT,
    T_UINT,
    T_LONG,
    T_DOUBLE,
    T_HEX,
    T_BINARY,
    T_FLOAT,
    T_NULL,
    T_IDENTIFIER,
    T_DOLLAR_IDENTIFIER,
    T_STRING,
    T_TAG,
    T_LINE_COMMENT,
    T_BLOCK_COMMENT,
    T_EOF,
    T_UNKNOWN,
};

struct LgsToken {
    LgsTokenType type = T_UNKNOWN;
    std::string lexeme = "";
    LgsLocation location;
    LgsToken() = default;
    LgsToken(const LgsTokenType type, const std::string& lexeme, const LgsLocation& location) : type(type), lexeme(lexeme), location(location) {}
};


const std::unordered_map<std::string, LgsTokenType> LGS_KEYWORDS = {
    {"type", T_TYPE},
    {"object", T_OBJECT},
    {"single", T_SINGLETON},
    {LGS_SELF, T_SELF_INSTANCE},
    {LGS_SELF_CLASS, T_SELF_CLASS},
    {"interface", T_INTERFACE},
    {"pub", T_PUBLIC},
    {"implements", T_IMPLEMENTS},
    {"mut", T_MUT},
    {"enum", T_ENUM},
    {"go", T_GO},
    {"defer", T_DEFER},
    {"io", T_IO},
    {"and", T_AND},
    {"or", T_OR},
    {"not", T_NOT},
    {"in", T_IN},
    {"if", T_IF},
    {"switch", T_SWITCH},
    {"else", T_ELSE},
    {"then", T_THEN},
    {"while", T_WHILE},
    {"break", T_BREAK},
    {"continue", T_CONTINUE},
    {"return", T_RETURN},
    {"import", T_IMPORT},
    {"for", T_FOR},
    {"for.i", T_FOR_I},
    {"for.ever", T_FOR_EVER},
    {"for.isFirst", T_FOR_IS_FIRST},
    {"for.isLast", T_FOR_IS_LAST},
    {"Vec2", T_VEC2},
    {"Vec3", T_VEC3},
    {"Vec4", T_VEC4},
    {"Set", T_SET},
    {"true", T_BOOL},
    {"false", T_BOOL},
    {LGS_NULL_LITERAL, T_NULL}
};
